### ISSUE TITLE
How about android version?

### ISSUE THREAD

**Issue by musicode** [wix/react-native-wordpress-editor#1]
I need a rich text editor for a long time, the project is very nice.

I have some questions as below:
1. can I custom the toobar icons? because the default wordpress icons is ugly and i just need 2 or 3 buttons.
2. when to release the android version?
3. Is react-native-navigation 2.0 compatible?

**Comment by artald** [comment]
Hi,

Regarding your questions:
1. The icons were already replaced (they are not the WordPress ones that appear in the screenshot). Currently there's no easy way to replace them since it is hard-coded in the WordPress code. We use our own fork of their code (as a git submodule) and try to keep the changes there to a minimum unless there's an important fix. So as I mentioned, we did replace the images there but there's no interface to do that dynamically.
2. Android version is currently in the works. Rough estimation is a couple of weeks.
3. Since we use it in our production code it will be compatible with `react-native-navigation` 2.0 for sure.

**Comment by yedidyak** [comment]
It's only going to be compatible with navigation 2.0 on Android. We are adding a feature in navigation to support native screens based on Fragments, that will be used by this project.

Currently on Android there's an option for disabling the HTML button, in future I will add the option of removing other buttons. I'll see about a way to set the icons dynamically on the JS side at some point.
